### ISSUE TITLE
Incorrect highlighting of multiline strings

### ISSUE THREAD

**Issue by xoposhiy** [laktak/sublime-hjson#2]
```
{
  haiku:
    '''
    JSON I love you.
    But strangled is my data.
    This, so much better.
    '''
}
```

![screenshot](http://c2n.me/39Xda0Q.png)

**Comment by laktak** [comment]
Sorry but I can't reproduce this in ST3 3065. What version are you using?

**Comment by xoposhiy** [comment]
ST3 3065
![](http://c2n.me/3a0neKH.png0)

**Comment by laktak** [comment]
Please update the Hjson package, I tweaked the syntax a bit.

**Comment by xoposhiy** [comment]
Fixed! Thank you!
