### ISSUE TITLE
High CPU usage

### ISSUE THREAD

**Issue by stevage** [laktak/sublime-hjson#3]
Tried this plugin a couple of times, but it quickly leads to very high CPU spikes on my MBP. I'm not sure how to be more specific, but I install it (Package Manager), load a file, make a few edits, and very quickly the fan is going, and there are something like 10 Sublime tasks at 25% each. I remove the package, and the problem goes away.

Sublime build 3083.

**Comment by laktak** [comment]
Could you try deleting the index? 

See http://www.sublimetext.com/forum/viewtopic.php?f=2&t=17866&start=0
