### ISSUE TITLE
Weird highlighting

### ISSUE THREAD

**Issue by ottob** [laktak/sublime-hjson#4]
This is valid hjson but the highlighting seems incorrect.

```
id: age
type: number
validations: {
  min: 0
  max: 200
}
version: 1
```

![screen shot 2016-02-12 at 09 36 41](https://cloud.githubusercontent.com/assets/67104/13002110/2a14588a-d16c-11e5-8385-33dd525073e6.png)

**Comment by laktak** [comment]
I think the syntax file still expects a `{}` at the root level.

I'll update this when I switch to the new SL3 syntax format (https://www.sublimetext.com/docs/3/syntax.html). This may take a while though.

**Comment by 0x80** [comment]
With the {} at root level I also get wrong highlighting. 

<img width="502" alt="screenshot 2016-03-05 19 34 42" src="https://cloud.githubusercontent.com/assets/1193520/13549592/6393422a-e309-11e5-8d7c-fbc66f640424.png">

**Comment by laktak** [comment]
Fixed.
